<?php

namespace app\admin\common;

use think\Controller;
use think\Session;
class Base extends Controller{

	protected function _initialize(){
		  
		parent::_initialize(); // TODO: Change the autogenerated stub

		//在公共控制器的初始化方法中,创建一个常量用来判断用户是否登录或已登录
        define('USER_ID', Session::get('user_id'));
	}

	 //判断用户是否登录,在后台入口调用
    protected function isLogin()
    {
        //如果登录常量为NULL,表示没有登录
        if (is_null(USER_ID)) {
            $this -> error('未登录,无权访问~~', 'login/index');
        }
    }

    //判断用户是否登录,在登录入口调用
    protected function alreadyLogin()
    {
        //如果登录常量为NULL,表示没有登录
        if (!is_null(USER_ID)) {
            $this -> error('已经登录,不要重复登录~~', 'login/index');
        }
    }


}

?>